services:
  db:
    image: postgres:16
    container_name: synthetic-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: synthetic
    ports:
      - "5432:5432"
    volumes:
      - synthetic_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  langfuse-db:
    image: postgres:16
    container_name: langfuse-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: langfuse
    volumes:
      - langfuse_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  langfuse:
    image: langfuse/langfuse:2
    container_name: langfuse
    restart: unless-stopped
    depends_on:
      langfuse-db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@langfuse-db:5432/langfuse
      NEXTAUTH_URL: http://localhost:3000
      #for local only
      NEXTAUTH_SECRET: 4c02a1a627396cacc18d128b3413f4047d50df171eeb467f7512c51eb2b3056f
      SALT: b0ed26f021dff6474eb55e9db4bf25e0
      ENCRYPTION_KEY: 5f03887e40b4424b3ce72ea7501bd02dcb161d2f6125af47f06248f2bd86689d
      TELEMETRY_ENABLED: "false"

volumes:
  synthetic_db_data:
  langfuse_db_data:
